training: !!bool "false"
device: "cuda"
unprocessed_data: '../../VoxCeleb2/wav/*/*/*.wav'
---
data:
    train_path: './train_tisv_norm_vox1_vox2'
    train_path_unprocessed: '../../VoxCeleb2/wav/dev/*/*.wav'
    test_path: '/domino/datasets/local/abishek_rw_dataset_workflow/test_tisv_vox1_attempt2'
    test_path_unprocessed: '/domino/datasets/local/abishek_rw_dataset_workflow/wav/*/*/*.wav'
    data_preprocessed: !!bool "true" 
    sr: 16000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 40 #Number of mel energies
    tisv_frame: 180 #Max number of time steps in input after preprocess
---   
model:
    hidden: 768 #Number of LSTM hidden layer units
    num_layer: 3 #Number of LSTM layers
    proj: 256 #Embedding size
    model_path: './speech_id_checkpoint_vox1_vox2/ckpt_epoch_30_batch_id_180115-Aug-2020_01:38:13.420387.pth' #Model path for testing, inference, or resuming training
---
train:
    N : 4 #Number of speakers in batch
    M : 5 #Number of utterances per speaker
    num_workers: 0 #number of workers for dataloader
    lr: 0.001
    epochs: 950 #Max training speaker epoch 
    log_interval: 30 #Epochs before printing progress
    log_file: './speech_id_checkpoint_vox1_vox2/Stats'
    checkpoint_interval: 1 #Save model after x speaker epochs
    checkpoint_dir: './speech_id_checkpoint_vox1_vox2'
    restore: !!bool "true" #Resume training from previous model path
---
test:
    N : 4 #Number of speakers in batch
    M : 6 #Number of utterances per speaker
    num_workers: 8 #number of workers for data laoder
    epochs: 10 #testing speaker epochs
